config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :teaching_sets, only: [:index] do
    resources :lessons, only: [:index, :show]
    resources :tasks, only: [:index, :create]
    resources :report_cycles, only: [:index]
    get 'events', to: 'events#filtered_index', defaults: { format: :json }
  end

  resources :lessons, only: [:update]

  resources :scores, only: [:update]
  resources :tasks, only: [:update, :destroy]
  resources :marks, only: [:create, :update]
  resources :reports, only: [:update]
  resources :events, only: [:index], defaults: { format: :json }
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to teaching_sets_path do  %>
    <%= image_tag "logo.png", alt: "logo", id: "navbar-logo" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "Timetable", teaching_sets_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <a href="" class="navbar-wagon-item navbar-wagon-link dropdown-toggle" data-toggle="dropdown">Classes</a>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <% current_user.teaching_sets.sort_by{|ts| ts.year_group}.sort_by{|ts| ts.subject}.each do |teaching_set| %>
            <li>
              <%= link_to teaching_set_tasks_path(teaching_set) do %>
                <%= teaching_set.year_group %>, <%= teaching_set.subject %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= image_tag "#{current_user.photo}", class: "avatar" %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Classes</a></li>
        <li><a href="#">Logout</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_tabbar.html.erb
<div class="tab-bar">
  <% teaching_set = TeachingSet.find(params[:teaching_set_id]) %>
  <h3><%= teaching_set.year_group %>, <%= teaching_set.subject %></h3>
  <div class="tabs">
    <%= link_to "Lessons", teaching_set_lessons_path(teaching_set), class: "tab #{'active' if @nav == 'lessons'}" %>
    <%= link_to "Marks", teaching_set_tasks_path(teaching_set), class: "tab #{'active' if @nav == 'marks'}" %>
    <%= link_to "Reports", teaching_set_report_cycles_path(teaching_set), class: "tab #{'active' if @nav == 'reports'}" %>
  </div>
</div>