config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :teaching_sets, only: [:index] do
    resources :lessons, only: [:index, :show]
    resources :tasks, only: [:index, :create]
    resources :report_cycles, only: [:index]
    get 'events', to: 'events#filtered_index', defaults: { format: :json }
  end

  resources :lessons, only: [:update]

  resources :scores, only: [:update]
  resources :tasks, only: [:update, :destroy]
  resources :marks, only: [:create, :update]
  resources :reports, only: [:update]
  resources :events, only: [:index], defaults: { format: :json }
end

app/models/lesson.rb
# == Schema Information
#
# Table name: lessons
#
#  id              :bigint(8)        not null, primary key
#  start_time      :datetime
#  end_time        :datetime
#  teaching_set_id :bigint(8)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Lesson < ApplicationRecord
  belongs_to :teaching_set
  belongs_to :report_cycle
  has_many :pupils, through: :teaching_set
  has_many :scores, dependent: :destroy
  after_create_commit :make_pupil_scores
  after_update_commit :make_pupil_scores
  # after_save :make_pupil_scores

  def make_pupil_scores
    self.teaching_set.set_pupils.each do |set_pupil|
      Score.create(
        lesson: self,
        set_pupil: set_pupil
        )
    end
  end

  def previous
    previous_lessons = self.teaching_set.lessons.map do |lesson|
      lesson if lesson.start_time < self.start_time
    end
    previous_lessons.compact.sort_by{ |l| l.start_time }.last
  end

  def next
    next_lessons = self.teaching_set.lessons.map do |lesson|
      lesson if lesson.start_time > self.start_time
    end
    next_lessons.compact.sort_by{ |l| l.start_time }.first
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @teaching_set = TeachingSet.find(params[:teaching_set_id])
    @lessons = Lesson.where(teaching_set: @teaching_set)
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    @lesson.update(lesson_params)
  end

  def nav_status
    @nav = "lessons"
  end

  private

  def lesson_params
    params.require(:lesson).permit(:comment)
  end
end

app/views/lessons/_comment_form.html.erb
<%= simple_form_for(score, remote: true) do |f| %>
  <%= f.input :comment, label: false, class: "form-control", placeholder: "Optional comment" %>
  <%= f.button :submit, value: "Save Comment", class: "btn-markbook" %>
<% end %>

app/views/lessons/_lesson_comment_form.html.erb
<%= simple_form_for(lesson, remote: true, html: {id: "lesson-comment-form"}) do |f| %>
  <%= f.input :comment, label: false, class: "form-control", id: "lesson-form", placeholder: "Anything to remember about this lesson?" %>
<% end %>

app/views/lessons/_minus_form.html.erb
<%= simple_form_for(score, remote: true) do |f| %>
  <input name="score[decrement]", type="hidden", value="<%= "#{score.value - 1}" %>">
  <%= button_tag type: "submit", class: "btn btn-card", id: "minus_#{score.id}" do %>
    <i class="fas fa-minus"></i>
  <% end %>
<% end %>

app/views/lessons/_plus_form.html.erb
<%= simple_form_for(score, remote: true) do |f| %>
  <input name="score[increment]", type="hidden", value="<%= "#{score.value + 1}" %>">
  <%= button_tag type: "submit", class: "btn btn-card", id: "plus_#{score.id}" do %>
    <i class="fas fa-plus"></i>
  <% end %>
<% end %>

app/views/lessons/index.html.erb
<div class="container">
  <br>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-offset-2 col-md-8">
      <div id="calendar-list"></div>
    </div>
  </div>
</div>
<div id="events-path" class="hidden"><%= teaching_set_events_path(@teaching_set) %></div>
<!-- <div class="container">
  <h1>Lessons for <%= @teaching_set.year_group %>, <%= @teaching_set.subject %></h1>
  <ul>
    <% @lessons.each do |lesson| %>
      <%= link_to teaching_set_lesson_path(lesson.teaching_set_id, lesson.id) do %>
      <li><%= lesson.start_time.strftime('%A, %d %b %Y %l:%M %p') %></li>
      <% end %>
    <% end %>
  </ul>
</div> -->

app/views/lessons/show.html.erb
<div class="container">
  <div class="row lesson-navigation">
    <%= link_to teaching_set_lessons_path(@lesson.teaching_set) do %>
      <i class="fas fa-list-ul icon-blue" id="font-larger"></i>
    <% end %>
    <div class="text-center" id="lesson-title">
      <h3><%= @lesson.start_time.strftime('%a, %e %b %Y - %H:%M') %></h3>
    </div>
    <div id="lesson-arrows">
      <% if @lesson.previous %>
        <%= link_to teaching_set_lesson_path(@lesson.teaching_set,@lesson.previous) do %>
          <i class="fas fa-caret-left fa-2x icon-blue"></i>
        <% end %>
      <% else %>
        <i class="fas fa-caret-left fa-2x text-muted"></i>
      <% end %>
      <% if @lesson.next %>
        <%= link_to teaching_set_lesson_path(@lesson.teaching_set,@lesson.next) do %>
          <i class="fas fa-caret-right fa-2x icon-blue"></i>
        <% end %>
      <% else %>
        <i class="fas fa-caret-right fa-2x text-muted"></i>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="lesson-comment-container">
      <%= render 'lessons/lesson_comment_form', lesson: @lesson %>
    </div>
  </div>

  <div class="row">
    <% @lesson.scores.sort_by {|score| score.set_pupil.pupil.last_name }.each do |score| %>
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
      <div class="pupil-card text-center">
        <h4><%= score.set_pupil.pupil.first_name %><br><%= score.set_pupil.pupil.last_name %></h4>
        <div id="avatarbuttons">
          <div id=<%= "minus_score_form_score_#{score.id}" %>>
            <%= render 'lessons/minus_form', score: score %>
          </div>

          <%= image_tag "#{score.set_pupil.pupil.photo}", class: "avatar" %>

          <div id=<%= "plus_score_form_score_#{score.id}" %>>
            <%= render 'lessons/plus_form', score: score %>
          </div>
        </div>
        <div id="score-container">
          <p class="score" id=<%= "score_#{score.id}" %>><%= score.value %></p>
        </div>
        <div class="comment-container" id=<%= "comment-container_#{score.id}" %>>
          <%= render 'lessons/comment_form', score: score %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>